In [95]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.1+cu121


## Introduction to Tensors

Tensors are a way to represnt data, especially multi-dimensional data, numeric data that is

## Creating Tensors
1. Scalar -
    PyTorch tensors are created using ``` torch.tensor() ```
2. Vector -
    A vector has magnitude and direction. ``` torch.tensor([7,7]) ```
3. MATRIX -
    A matrix is of dim n dim with shape of n x m.  ``` torch.tensor([[7,8],[9,10]]) ```

In [96]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [97]:
scalar.ndim

0

In [98]:
scalar.item()

7

In [99]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [100]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [101]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                         [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [102]:
TENSOR.shape

torch.Size([1, 3, 3])

here ``` torch.size([1,3,3]) ``` one tensor of 3 X 3


### Random tensors

why random tensors ?

Random tensors are important because the way many nueral network learns is that they startwith tensors full of random numbers and then adjust those random numbers to better represent the data.
` Start with random number -> look at data -> update random numbers -> look at data -> update random number `

In [103]:
#create a random tensor of sixe (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5509, 0.8985, 0.9051, 0.2328],
        [0.7790, 0.8235, 0.4036, 0.7174],
        [0.5647, 0.5848, 0.3478, 0.9317]])

In [104]:
random_tensor.ndim

2

In [105]:
# creaet a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (224,224,3)) # height, weight, color channels
random_image_size_tensor.shape

torch.Size([224, 224, 3])

# zeros and Ones

In [106]:
# creating a tensor of all zeros
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [107]:
zeros.dtype

torch.float32

### Creating a range of tensors and tensors-like

we can use ``` torch.range(start,end,step) ``` if the range function is not working then use ``` torch.arange(start,end,step) ```

In [108]:
# use torch.range()
one_to_ten = torch.range(1,11)
one_to_ten

<ipython-input-108-6be76beb685d>:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1,11)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [109]:
step_range = torch.range(start = 0, end = 1000, step = 77)
step_range

<ipython-input-109-80c5e09906ea>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  step_range = torch.range(start = 0, end = 1000, step = 77)


tensor([  0.,  77., 154., 231., 308., 385., 462., 539., 616., 693., 770., 847.,
        924.])

In [110]:
# Creating a tensors like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### Tensor Datatypes

3 Important parameters for ``` torch.tensor([1,2,3,4], dtype = , device = , requires_grad = True/False) ```

1. dtype - specifies the data tyep of tensors element ( float 32, float 16 )
2. device - lets us access the runtime i.e CPU/ GPU/ TPU
3. requires_grad - boolean type (if you want pytorch to track gradients set the value to true )

### Errors in Tensors datatypes

**Note:** Tensor datatypes is one of the 3 big errors you will run into with pytorch & Deep Learning

1. Tensors not right datatypes
2. Tensors not right shape
3. Tesnosrs not on the right device


In [111]:
# float 32 tensor
float_32_tensor = torch.tensor([3.0,6.0,9.0], dtype = None)
float_32_tensor   # by default the tensor data type is float only

tensor([3., 6., 9.])

In [112]:
float_32_tensor.dtype

torch.float32

In [113]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [114]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors

1. Tensors not right datatypes - use `tensor.dtype`
2. Tensors not right shape - use `tensor.shape`
3. Tesnosrs not on the right device - use `tensor.device`



In [115]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7185, 0.8491, 0.6393, 0.5080],
        [0.8001, 0.0901, 0.0426, 0.6774],
        [0.0510, 0.8361, 0.6035, 0.9898]])

In [116]:
print(some_tensor)
print(f"Datatype of the tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.7185, 0.8491, 0.6393, 0.5080],
        [0.8001, 0.0901, 0.0426, 0.6774],
        [0.0510, 0.8361, 0.6035, 0.9898]])
Datatype of the tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors

Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [117]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [118]:
tensor*10

tensor([10, 20, 30])

In [119]:
# in-built fnction
torch.mul(tensor,10)

tensor([10, 20, 30])

### Matrix multiplication

Two main ways of performing multiplication in neural netwrok and deep learning

1. Element-wise multiplication
2. Matrix multiplication (dot product)

In [120]:
# Element wise mulltiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [121]:
# matrix multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [122]:
tensor1 = torch.tensor([[1,2,3],
                        [4,5,6]])
tensor2 = torch.tensor([[7,8],
                        [9,10],
                        [11,12]])

torch.matmul(tensor1,tensor2)

tensor([[ 58,  64],
        [139, 154]])

In [123]:
tensor1 = tensor1.T

In [124]:
tensor2 = tensor2.T
tensor2

tensor([[ 7,  9, 11],
        [ 8, 10, 12]])

In [125]:
torch.mm(tensor1,tensor2)

tensor([[ 39,  49,  59],
        [ 54,  68,  82],
        [ 69,  87, 105]])

## Finding the min, Max, Mean, Sum and etc

In [126]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [127]:
#Min
torch.min(x)

tensor(0)

In [128]:
#Max
torch.max(x)

tensor(90)

In [129]:
# Find the mean
torch.mean(x.type(torch.float32))

tensor(45.)

In [130]:
# find the sum
torch.sum(x)

tensor(450)

### Reshaping, Stacking, Squeezing, and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an inout tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on the top of each other or side by side
* Squeeze - Removes all `1` dimensions from a tensor
* Unsqueeze - Add a `1` dimension to a target tensor
* Permute - Return a view of the inout with dimensions permuted in a certain way

In [131]:
x = torch.arange(1.,10.,)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [132]:
# Reshape
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
#change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [134]:
#stacks tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked


tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [135]:
# squeeze operation - removes all the single dimensions from the taget tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [136]:
# unsqueeze - add a single a dimenson to the target tensor
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")



New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [137]:
# Permute -  rearranges the dimensions of a target tensor in a  specific order
y = torch.rand(size = (224,224,3))

# Permute the original tensor to rearrange
x_permuted = y.permute(2,0,1) # shifts axis 0->1, 1->2, 2->0
print(f"Pervious Shape: {y.shape}")
print(f"New shape: {x_permuted.shape}")

Pervious Shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


### Indexing (Selecting data from tensors)

Indexing with pyTorch is similar to indexing with Numpy

In [138]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [139]:
#Lets Index on our tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [142]:
x[0][2][2]

tensor(9)

In [143]:
# get all the values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

### PyTorch tensors & Numpy

NumPy is a popular scientific Python numerical computing library.
and because of this, Pytorch has functionally to interact with it

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [144]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [145]:
# change the value of array, what will this do to 'tensor' ?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [149]:
# Tensor to NumPy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random )

In short how a neura network learns:

` Start with random numbers -> tensor operations-> update random number to try and make the better representation of data -> again ->again `

To reduce the randomness in neural netwroks and PyTorch comes the concept of a **Random Seed**.

Essentially what the random seed does is "Flavour" the randomness.

In [150]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.2938, 0.7767, 0.8585, 0.5708],
        [0.0114, 0.5387, 0.8668, 0.1611],
        [0.4735, 0.0230, 0.6241, 0.3162]])
tensor([[0.2178, 0.3268, 0.9812, 0.0377],
        [0.8917, 0.9320, 0.4808, 0.7727],
        [0.1922, 0.7478, 0.7733, 0.3893]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [152]:
# lets amke some random but reproducible tensors

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
### Running tensor and PyTorh objects on the GPUs
